### ISSUE TITLE
Allow to configure different XML/JSON serializers

### ISSUE THREAD

**Issue by willdurand** [willdurand/BazingaHateoasBundle#12]
How should we handle this? Configuration?

``` yaml
bazinga_hateoas:
    serializer:
      xml: My\Custom\XmlSerializer
      json: My\CustomJsonSerializer
```
