### ISSUE TITLE
Ability to configure arbitrary EL variables

### ISSUE THREAD

**Issue by adrienbrault** [willdurand/BazingaHateoasBundle#13]
WDYT of being able to configure EL variables, that would be a bit like twig global variables:

``` yaml
bazinga_hateoas:
    expression_language:
        context_variables:
            base_rel: https://rels.example.com
            foo: bar
```

To then be able to:

``` php
/**
 * @Hateoas\Relation("expr(base_rel ~ '/users')", ...)
 */
```
