### ISSUE TITLE
UrlGeneratorPass incompatible with class parameters

### ISSUE THREAD

**Issue by cblegare** [willdurand/BazingaHateoasBundle#21]
Given a custom url generator defined as a service :

``` yml
parameters:
    my.url_generator.class:
        Acme\Foo\MyUrlGenerator
services:
    my.url_generator:
        class: %my.url_generator.class%
    tags:
        -
            name: hateoas.url_generator
            alias: my_url_generator
```

When I compile the container
Then the UrlGeneratorPass fails because it tries to construct a ReflectionClass from the string `%my.url_generator.class%`.

Over there : https://github.com/willdurand/BazingaHateoasBundle/blob/master/DependencyInjection/Compiler/UrlGeneratorPass.php#L54

I understand that this is used to avoid vendor lock-in and to trim the Symfony [`UrlGeneratorInterface`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Generator/UrlGeneratorInterface.php) from superfluous methods.  But the check seams plain wrong in this specific case.
