### ISSUE TITLE
How to configure Metadata directories

### ISSUE THREAD

**Issue by ohaag** [willdurand/BazingaHateoasBundle#52]
Question:
In the library's documentation, there is a point [Configuring Metadata Locations](https://github.com/willdurand/Hateoas#configuring-metadata-locations).
However, I don't understand how to apply that with the bundle: nowhere is mentioned how we have to use the HateoasBuilder in the bundle.

I think by code inspection that, it could be managed with the Metadata/Driver/DriverChain of jms/serializer but I don't understand how.

For example, I want to do the same thing with HateoasBundle than I do here with JMSSerializerBundle:

```
jms_serializer:
    metadata:
        directories:
            DoctrinePHPCR:
                namespace_prefix: "Doctrine\\ODM\\PHPCR"
                path: "@AppBundle/Resources/config/serializer/DoctrinePHPCR"
```
